name: Dayoung Lee
author: Dayoung Lee
baseurl: ""
url: "https://ataraxiady.github.io"
description: Dev\nCurrently in Korea
github: http://www.github.com/ataraxiady
linkedin: https://www.linkedin.com/in/dayoung-lee-91a011187/
email: ataraxiady@gmail.com
location: Korea, Republic of
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
